openapi: 3.0.2
info:
  title: ""
  version: ""
paths:
  /jogo_da_memoria/:
    get:
      description:
        "Caso n\xE3o exista nenhum jogo instanciado pelo jogador, cria\
        \ um novo, salva na sess\xE3o e retorna os n\xFAmeros das cartas.\nCaso\
        \ j\xE1 exista um jogo instanciado, retorna o jogo."
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  jogo:
                    type: array
                    maxItems: 8
                    uniqueItems: true
                    items:
                      type: integer
                example:
                  jogo:
                    - "94812983"
                    - "12321331"
                    - "31231233"
                    - "65645645"
                    - "63546363"
                    - "62462466"
                    - "62345253"
                    - "87686788"
      tags:
        - jogo-da-memoria
    post:
      description:
        "Recebe um par de cartas e faz um movimento.\nRetorna as cartas\
        \ enviadas, os valores das cartas, acertos e jogadas.\nCaso o jogo tenha encerrado,\
        \ registra a pontua\xE7\xE3o do jogador."
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                carta1:
                  type: string
                carta2:
                  type: string
              example:
                carta1: "5257967988"
                carta2: "72689513"
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  teste:
                    type: string
                  carta1:
                    type: string
                  carta2:
                    type: string
                  valor_carta1:
                    type: integer
                  valor_carta2:
                    type: integer
                  jogadas:
                    type: integer
                  acertos:
                    type: integer
                example:
                  carta1: "5257967988"
                  carta2: "72689513"
                  valor_carta1: 2
                  valor_carta2: 1
                  jogadas: 3
                  acertos: 1
      tags:
        - jogo-da-memoria
    delete:
      description: "Deleta a instância de jogo vinculada ao usuário."
      parameters: []
      responses:
        "204":
          description: ""
      tags:
        - jogo-da-memoria
  /jogo_da_memoria/ranking/:
    get:
      description: Retorna uma lista com o ranking.
      parameters:
        - name: page
          required: false
          in: query
          description: A page number within the paginated result set.
          schema:
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=4
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?page=2
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        jogadas:
                          type: integer
                        erros:
                          type: integer
                        user_data:
                          type: object
                          properties:
                            id:
                              type: integer
                            username:
                              type: integer
          description: ""
      tags:
        - jogo-da-memoria
  /accounts/login/:
    post:
      description: Recebe username e senha, retorna um token caso autenticado.
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/AuthToken"
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/AuthToken"
          application/json:
            schema:
              $ref: "#/components/schemas/AuthToken"
      responses:
        "201":
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_data:
                    type: object
                    properties:
                      username:
                        type: string
                  token:
                    type: string
              example:
                user_data:
                  username: "usuario1"
                token: "a8c511d86fad6d79195928ba7e83b18b2ea3c231"

          description: ""
      tags:
        - accounts
  /accounts/register/:
    post:
      operationId: createUsuario
      description: "Recebe username e senha do usu\xE1rio e efetua o cadastro."
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Usuario"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/Usuario"
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/Usuario"
      responses:
        "201":
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_data:
                    type: object
                    properties:
                      username:
                        type: string
              example:
                user_data:
                  username: "usuario1"

          description: ""
      tags:
        - accounts
components:
  schemas:
    Ranking:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        usuario:
          type: object
          properties:
            id:
              type: integer
              readOnly: true
            username:
              type: string
              description:
                "Obrigat\xF3rio. 150 caracteres ou menos. Letras, n\xFA\
                meros e @/./+/-/_ apenas."
              pattern: ^[\w.@+-]+\z
              maxLength: 150
            password:
              type: string
              writeOnly: true
              maxLength: 128
          required:
            - username
            - password
        jogadas:
          type: integer
        erros:
          type: integer
      required:
        - usuario
        - jogadas
        - erros
    AuthToken:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        token:
          type: string
          readOnly: true
      required:
        - username
        - password
    Usuario:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          description:
            "Obrigat\xF3rio. 150 caracteres ou menos. Letras, n\xFAmeros\
            \ e @/./+/-/_ apenas."
          pattern: ^[\w.@+-]+\z
          maxLength: 150
        password:
          type: string
          writeOnly: true
          maxLength: 128
      required:
        - username
        - password
