# Generated by Django 3.2.9 on 2021-11-29 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jogo_da_memoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JogoDaMemoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartas', models.JSONField()),
                ('parsed_cartas', models.JSONField()),
                ('jogadas', models.IntegerField()),
                ('acertos', models.IntegerField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
