# Generated by Django 3.2.9 on 2021-12-18 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jogo_da_memoria', '0002_jogodamemoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jogodamemoria',
            old_name='parsed_cartas',
            new_name='cartas_map',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='jogadas',
        ),
        migrations.AddField(
            model_name='jogodamemoria',
            name='carta_anterior',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
